x-login:
  &ghcr-login
  command: >
    sh -c "echo $GITHUB_PAT | docker login ghcr.io -u $GITHUB_USERNAME --password-stdin"

services:
  mysql:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3308:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-ppassword"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - ekalavya-net

  ekalavya-web:
    image: ghcr.io/ekalavya-io/ekalavya-web:dev
    container_name: ekalavya-web
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - ekalavya-erp-service
      - ekalavya-scratch-editor
    networks:
      - ekalavya-net

  ekalavya-users-service:
    image: ghcr.io/ekalavya-io/ekalavya-users-service:dev
    container_name: ekalavya-users-service
    restart: always
    ports:
      - "9001:9001"
    env_file:
      - ./env/ekalavya-users-service.env
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - ekalavya-net

  ekalavya-content-service:
    image: ghcr.io/ekalavya-io/ekalavya-content-service:dev
    container_name: ekalavya-content-service
    restart: always
    ports:
      - "9002:9002"
    env_file:
      - ./env/ekalavya-content-service.env
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - ekalavya-net

  ekalavya-erp-service:
    image: ghcr.io/ekalavya-io/ekalavya-erp-service:dev
    container_name: ekalavya-erp-service
    restart: always
    ports:
      - "9003:9003"
    env_file:
      - ./env/ekalavya-erp-service.env
    depends_on:
      mysql:
        condition: service_healthy
      ekalavya-users-service:
        condition: service_started
      ekalavya-content-service:
        condition: service_started
      ekalavya-files-service:
        condition: service_started
    networks:
      - ekalavya-net

  ekalavya-files-service:
    image: ghcr.io/ekalavya-io/ekalavya-file-upload-service:dev
    container_name: ekalavya-files-service
    restart: always
    ports:
      - "9005:9005"
    env_file:
      - ./env/ekalavya-files-service.env
    volumes:
      - ./app-files:/app/files
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - ekalavya-net

  ekalavya-scratch-editor:
    image: ghcr.io/ekalavya-io/ekalavya-scratch-editor:dev
    container_name: ekalavya-scratch-editor
    restart: always
    ports:
      - "8601:80"
    networks:
      - ekalavya-net
      
networks:
  ekalavya-net:
    driver: bridge